name: Create Release ZIP

on:
  push:
    tags:
      - '*'
  workflow_dispatch:   # Manuelles Auslösen hinzufügen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Get the tag from git
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "Current tag is: $TAG_NAME"
          echo "GIT_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          # Verwendet die Umgebungsvariable GIT_TAG
          echo "Using tag: $GIT_TAG"

          # Erstelle einen Ordner mit dem Tag-Namen
          mkdir -p dist/sudoku120publisher

          # Stelle sicher, dass die erweiterte Mustererweiterung aktiviert ist
          shopt -s extglob

          # Kopiere alle Dateien in den Ordner, außer den Verzeichnissen dist und assets
          cp -R !(dist|assets|.github) dist/sudoku120publisher/

          # Erstelle das ZIP-Archiv mit dem Tag-Namen im Dateinamen
          cd dist
          zip -r sudoku120publisher-${GIT_TAG}.zip sudoku120publisher -x .git\* README.md

      - name: Upload ZIP as GitHub Release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/sudoku120publisher-${GIT_TAG}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
