name: Create Release ZIP

on:
  push:
    tags:
      - '*'
  workflow_dispatch:   # Manuelles Auslösen hinzufügen

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Berechtigung zum Schreiben von Inhalten
      actions: write   # Berechtigung zum Erstellen von Aktionen und Releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Schritt: Git-Historie aktualisieren, um alle Tags und Commits verfügbar zu machen
      - name: Fetch full history
        run: git fetch --prune --unshallow

      - name: Get the tag from git
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "Current tag is: $TAG_NAME"
          echo "GIT_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          # Verwendet die Umgebungsvariable GIT_TAG
          echo "Using tag: $GIT_TAG"

          # Erstelle einen Ordner mit dem Tag-Namen
          mkdir -p dist/sudoku120publisher

          # Kopiere Dateien (ausgeschlossen: dist, assets, .github)
          rsync -av --exclude='dist' --exclude='assets' --exclude=".*" --exclude='phpcs.xml.dist' --exclude='composer.json' --exclude='README.md' --exclude='README_*.md' ./ dist/sudoku120publisher/

          # Erstelle das ZIP-Archiv mit dem Tag-Namen im Dateinamen
          cd dist
          zip -r sudoku120publisher-${GIT_TAG}.zip sudoku120publisher -x .git\* README.md

      - name: Debug - List dist directory
        run: ls dist/

      - name: Upload ZIP as GitHub Release asset
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ env.GIT_TAG }}"
          tag_name: ${{ env.GIT_TAG }}
          files: dist/sudoku120publisher-${{ env.GIT_TAG }}.zip
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
